### ISSUE TITLE
pre-commit hooks (gci & golines)

### ISSUE THREAD

**Issue by moshe-blox** [ssvlabs/ssv#2127]
@iurii-ssv i think thats ok for now

turns out VSCode Go extension doesn't let you use goimports very easily, however gopls should produce the same output as long as you format the document (only issue for some devs maybe be that autosave doesn't trigger import sorting).

opening an issue to try a pre-commit hook to improve dev UX

if it works out nicely, then we can consider even upgrading to non-conventional post-processing steps (such as gci and golines)

---
### **Git Hooks (Pre-commit Hook)**
**Approach:**  
Use a `pre-commit` hook to auto-run `make format` before each commit.

**Pros:**
- Runs automatically, no need to remember.
- Can block commits with formatting errors.

**Cons:**
- Needs to be installed locally per dev (not enforced by Git).
- If not managed well, it can drift or break.

**Best practice:**  
Use [`[pre-commit](https://pre-commit.com/)`](https://pre-commit.com/) framework with a shared config committed in the repo:
```yaml
# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: make-format
        name: Run make format
        entry: make format
        language: system
        types: [python, go, ...]
```
Then instruct devs to run:
```bash
pre-commit install
```

To **enforce it**, CI should check formatting again and fail if formatting is skipped.

_Originally posted by @moshe-blox in https://github.com/ssvlabs/ssv/issues/2045#issuecomment-2781466889_
